import { useState } from 'react';
import { ArrowDown, ArrowUpRight, CalendarPlus, Heart, MapPin, MessageCircle, Phone, Share2, Sparkles, UtensilsCrossed } from 'lucide-react';
import temple from '../assets/temple.png';
import { GOOGLE_MAPS_DIRECTIONS_URL, GOOGLE_MAPS_EMBED_URL, WHATSAPP_RSVP_URL, FAMILY_CONTACT_NUMBER, INVITATION_URL, SHARE_INVITATION_MESSAGE } from './weddingData';
import './invitation.css';

const events = [
  { title: 'An evening together', label: 'The wedding dinner', date: 'Sunday, 21 June 2026', time: '7:00 PM onwards', start: '20260621T190000', end: '20260621T223000', Icon: UtensilsCrossed, description: 'Good food, familiar faces, and the joy of two families coming together.' },
  { title: 'The sacred beginning', label: 'Wedding muhurtham', date: 'Monday, 22 June 2026', time: '2:32 AM', start: '20260622T023200', end: '20260622T043000', Icon: Sparkles, description: 'Join us for the sacred vows in the early hours of Monday, following dinner.' },
];
function calendarLink(event) {
  return `https://calendar.google.com/calendar/render?${new URLSearchParams({ action: 'TEMPLATE', text: `Praveen & Priyanka — ${event.label}`, dates: `${event.start}/${event.end}`, ctz: 'Asia/Kolkata', location: 'S.V. Function Hall, J.N. Road, Rajamahendravaram', details: INVITATION_URL })}`;
}
export default function ClassicInvitation() {
  const [status, setStatus] = useState('');
  async function share() {
    try {
      if (navigator.share) await navigator.share({ title: 'Praveen & Priyanka Wedding', text: SHARE_INVITATION_MESSAGE });
      else { await navigator.clipboard.writeText(SHARE_INVITATION_MESSAGE); setStatus('Invitation copied. Ready to share!'); }
    } catch (error) { if (error.name !== 'AbortError') setStatus('Please copy the invitation link from your browser to share.'); }
  }
  return <div className="invitation">
    <a className="skip-link" href="#celebration">Skip to wedding details</a>
    <header className="site-header"><a className="monogram" href="#home" aria-label="Praveen and Priyanka home">P<span>&</span>P</a><nav aria-label="Main navigation"><a href="#celebration">Celebration</a><a href="#family">Our family</a><a href="#venue">The venue</a></nav><a className="header-rsvp" href="#rsvp">You're invited <ArrowUpRight size={15}/></a></header>
    <main>
      <section className="hero-section" id="home"><div className="hero-copy"><p className="eyebrow">Together with our families</p><p className="hero-intro">With love, we invite you to celebrate</p><h1>Praveen <span className="ampersand">&</span> Priyanka</h1><div className="hero-date"><span>21</span><div>JUNE 2026<small>Sunday evening · 7:00 PM onwards</small></div></div><p className="hero-description">Two hearts. Two families. One beautiful beginning.<br/>Your presence is the blessing we cherish most.</p><a className="button primary" href="#celebration">Explore the celebration <ArrowDown size={16}/></a><p className="hero-location"><MapPin size={14}/> Rajamahendravaram, Andhra Pradesh</p></div><div className="hero-art"><div className="arch-frame"><span className="arch-blessing" lang="te">శుభమస్తు</span><div className="sun-disc"/><img src={temple} alt="An ornate South Indian temple gopuram" width="2772" height="3508" fetchPriority="high"/><span className="art-caption">Rooted in tradition. United in love.</span></div><div className="wedding-seal" aria-hidden="true"><span>WITH LOVE</span><Heart size={22} strokeWidth={1}/><span>21 · 06 · 26</span></div></div></section>
      <div className="blessing-strip"><span>LOVE</span><span aria-hidden="true">✧</span><span>FAMILY</span><span aria-hidden="true">✧</span><span>TRADITION</span><span aria-hidden="true">✧</span><span>FOREVER</span></div>
      <section id="celebration" className="section"><div className="section-heading"><p className="eyebrow">The wedding celebration</p><h2>A little celebration.<br/><em>A lifetime of togetherness.</em></h2><p>Join us on Sunday evening for dinner and stay for the sacred<br className="desktop-break"/> muhurtham in the early hours of Monday.</p></div><div className="event-grid">{events.map((event, index) => <article className="event-card" key={event.start}><div className="event-top"><event.Icon size={25} strokeWidth={1.3}/><span>0{index + 1}</span></div><p className="eyebrow">{event.label}</p><h3>{event.title}</h3><p className="event-description">{event.description}</p><div className="event-date"><strong>{event.date}</strong><span>{event.time} <small>IST</small></span></div><a className="text-link" href={calendarLink(event)} target="_blank" rel="noreferrer"><CalendarPlus size={16}/> Add to calendar <ArrowUpRight size={15}/></a></article>)}</div></section>
      <section className="love-band"><p className="eyebrow">A moment to cherish</p><h2>The beginning of our forever</h2><p>With your blessings, a beautiful new chapter begins.</p></section>
      <section id="family" className="section family-section"><div className="family-keepsake"><span className="eyebrow">With love & blessings</span><span className="family-initials">P & P</span><span>Two families. One beautiful beginning.</span></div><div className="family-copy"><p className="eyebrow">With the blessings of our elders</p><h2>Surrounded by family.<br/><em>Celebrated with love.</em></h2><div className="small-ornament" aria-hidden="true">✧</div><p>With the blessings of Gummadi Anand, Smt. Lokeswari, and our beloved elders, we request the honour of your presence as Praveen and Priyanka begin their sacred journey together.</p><p className="family-signature">With love, the Gummadi family</p></div></section>
      <section id="venue" className="venue-section"><div className="venue-copy"><p className="eyebrow">Meet us here</p><h2>A special place.<br/><em>A beautiful memory.</em></h2><h3>S.V. Function Hall</h3><p>J.N. Road, Rajamahendravaram<br/>Andhra Pradesh</p><a className="button primary" href={GOOGLE_MAPS_DIRECTIONS_URL} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={16}/></a><div className="family-contacts"><p className="eyebrow">Need a little help getting here?</p><a href={`tel:${FAMILY_CONTACT_NUMBER}`}><Phone size={14}/>{FAMILY_CONTACT_NUMBER}</a></div></div><div className="venue-map"><iframe title="S.V. Function Hall wedding venue map" src={GOOGLE_MAPS_EMBED_URL} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></section>
      <section id="rsvp" className="section rsvp-section"><Heart size={28} strokeWidth={1}/><p className="eyebrow">An invitation from the heart</p><h2>It wouldn’t be the same<br/><em>without you.</em></h2><p>Your presence will make our celebration complete.<br/>Come for the moments. Stay for the memories.</p><div className="rsvp-actions"><a className="button primary" href={WHATSAPP_RSVP_URL} target="_blank" rel="noreferrer"><MessageCircle size={17}/> RSVP on WhatsApp</a><button className="button secondary" onClick={share} type="button"><Share2 size={16}/> Share invitation</button></div><p className="share-status" role="status">{status}</p></section>
    </main><footer><a href="#home" className="monogram" aria-label="Back to top">P<span>&</span>P</a><p>Praveen & Priyanka <span>·</span> 21 June 2026</p><small>Made with love by Praveen</small></footer>
  </div>;
}
